Use mentions for users in mod logs and infraction search results
python-discord/bot pull request #1061
Opened 2020-07-21 17:27 UTC by MarkKoz

Fixes #533 
Fixes #337

## Mentions

Mod logs and infraction searches will now display a mention for users, including actors when dealing with infractions. The username and discriminator are also displayed for users. This ensures someone can still be identifiable at a glance in case the user isn't in the cache and the mention fails.

![User banned](https://user-images.githubusercontent.com/1515135/88085448-b39a5880-cb3a-11ea-87e0-898b2dc47e08.png)

![Member updated](https://user-images.githubusercontent.com/1515135/88086334-0aecf880-cb3c-11ea-86cf-36d3daef82bf.png)

![Infraction search](https://user-images.githubusercontent.com/1515135/88085826-3b806280-cb3b-11ea-8253-fc94bfc7802c.png)

![Filter triggered](https://user-images.githubusercontent.com/1515135/88086760-b8600c00-cb3c-11ea-82ae-eea482a28a08.png)

If the user's name and discriminator isn't available, it is simply omitted. For example, this is the case when a user is unbanned:

![User unbanned](https://user-images.githubusercontent.com/1515135/88085696-0d028780-cb3b-11ea-9538-fe1af7d74966.png)

### Channel mentions

I have changed a few channels to use mentions when I've encountered them. However, all the channel mod logs have been left alone. Should those be changed to use mentions? Keep in mind such a change will mean they're no longer searchable as text, unless their names are included in plain text in addition to the mention.

## Misc changes

1. The code to send mod logs for triggered filters has been refactored to reduce code redundancy.
2. Multiple active infractions are no longer checked for when pardoning an infraction. The API will already reject a second active infraction of the same type.

2020-08-10 19:08 UTC, MarkKoz commented on bot/cogs/moderation/management.py
> +            user_str = f"<@{user['id']}> ({name}#{user['discriminator']})"
Fixed in 3c6cb81e6e36aa3e7321a92ea4e6625f99b3ce7c

2020-08-10 19:08 UTC, MarkKoz commented on tests/bot/cogs/test_token_remover.py
> +            author=f"{self.msg.author.mention} ({self.msg.author})",
Fixed in 5051b5aeccd1f33ba34b2dd2af03511343b60efd

2020-08-10 19:08 UTC, MarkKoz commented on bot/cogs/moderation/modlog.py
> +        message = format_user(member)
Fixed in 5d953b55ef7db247c009d5caae61fa3b1df8ff3e

2020-08-10 19:09 UTC, MarkKoz commented on bot/cogs/clean.py
>              f"A log of the deleted messages can be found [here]({log_url})."
I prefer 100 and only use 120 if it'd be more of a hassle to split something up. In this case, the string is going to be on multiple lines either way.

2020-08-10 19:10 UTC, MarkKoz commented
@Numerlor I believe a fetch is done to have a clear distinction between users and reasons. Keep in mind, sometimes queries are done on users that are not in the guild. In such cases, relying on the cache will not work.

2020-08-10 20:08 UTC, Numerlor commented
> @Numerlor I believe a fetch is done to have a clear distinction between users and reasons. Keep in mind, sometimes queries are done on users that are not in the guild. In such cases, relying on the cache will not work.

Only case I can think of where there would be a difference between fetching from the api and trying to validate a provided ID is where a valid user ID is provided, but the user doesn't exist. Is such an edge case worth it when all the user infraction data is fetched from the site after that anyway?

2020-08-10 22:27 UTC, MarkKoz commented
How do you propose to distinguish between an ID and a reason that happens to be a number?

2020-08-10 22:43 UTC, Numerlor commented
The user IDs are snowflakes, if we parse the datetime inside the number and it's a valid creation datetime then it should be safe to assume that an ID was looked up instead of a reason string

2020-08-11 23:36 UTC, MarkKoz commented
I think it's best to save that for another PR. It's more work than it first seems. The group invokes the subcommand, which expects a `discord.User` object.

2020-08-12 00:40 UTC, Numerlor commented
After matching it, it should be enough to just let it through an `UserConverter` and falling back to `proxy_user` like the command does, but yeah I agree that it is a bit out of scope here if the fetched user is not reused in the listing but the fetching removed.

2020-08-12 00:42 UTC, MarkKoz commented
Invoke uses the callback directly, without processing converters, checks, etc. The ID would need to manually be converted to a User. It's all a bit awkward.

2020-09-19 13:44 UTC, Senjan21 requested changes
Looks very solid, just 1 small change

2020-09-19 13:44 UTC, Senjan21 commented on bot/cogs/filtering.py
> +            f"{channel_str} {eval_msg}with [the following message]({msg.jump_url}):\n\n"
`eval_msg` should end with a space if the `is_eval` is set to `True`
Otherwise we will end with
`... via DM using !evalwith ...` as an example.

2020-09-19 18:52 UTC, MarkKoz commented on bot/cogs/filtering.py
> +        eval_msg = "using !eval" if is_eval else ""
```suggestion
        eval_msg = "using !eval " if is_eval else ""
```

2020-09-19 20:29 UTC, Senjan21 approved these changes
LGTM

2020-09-22 21:06 UTC, Numerlor approved these changes

2020-09-22 22:36 UTC, merged