Restrict nsfw subreddit(s) or similar
python-discord/bot pull request #1157
Opened 2020-09-15 07:06 UTC by RohanJnr

closes #1153 

### Changes made to Reddit Cog:
- Check if the subreddit is NSFW or similar by using the `over_18` boolean value got with the API response.
 - if True, then send an error message.
 - if False, the fetched data is sent to the user.

- A small change to the return format of the `fetch_posts()` method, instead of returning an empty `list` in case of an error, it now returns a list, with a `dict` containing the error message. This is done in order to distinguish between the NSFW restriction error message and network/connection/failed to connect to API error.

### Pending

- Unfortunately, I cannot test this as my account is restricted to view any NSFW subreddits due to age and country (whenever I send a request to an NSFW subreddit, I get a 451 status code - Unavailable For Legal Reasons).
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451
- If anyone above 18 years of age, having a  Reddit account, and living in a country that allows users to view NSFW content on Reddit, can test this feature, it will be helpful!

2020-09-22 21:46 UTC, Numerlor commented
I believe filtering posts and only sending the NSFW error message when no posts pass the filter would be a better option here, currently if the first fetched post happens to be NSFW while none of the others are, the user will get no output.

2020-09-23 13:24 UTC, RohanJnr commented
I think a better approach will be to check if any 1 of the posts does not pass the filter, then send nothing.
This is because, if we query for NSFW subreddit posts from the bot, then we don't want to send any posts, even tho is post is not entirely NSFW, we want to block the subreddit.

2020-09-30 09:10 UTC, kosayoda requested changes
Thanks for the pull request!

1. Regarding NSFW subreddits: Subreddits marked as over 18 will have all the posts marked over 18, so it shouldn't be an issue.
2. Rather than telling the user about the subreddit being out of scope, the error message when no posts are found should just be `... couldn't find any SFW posts from that subreddit...`. That way it is clearer and easier to handle in the code.
3. Error handling should be in `get_top_posts` rather than `fetch_posts`, which would basically be what it is originally.

2020-10-16 21:12 UTC, Numerlor commented on bot/exts/info/reddit.py
> -
Any reason for the removal of the newline here?

2020-10-17 04:39 UTC, kosayoda approved these changes
Works well in testing now, awesomesauce.

2020-10-17 09:30 UTC, kwzrd approved these changes
Works great, thanks for the fix. There is a good opportunity to test against [r/test](https://old.reddit.com/r/test)'s top weekly posts:

![image](https://user-images.githubusercontent.com/44734341/96333752-f7cec380-106b-11eb-9e58-49736b66229a.png)

Also works against NSFW-only subs.

2020-10-17 09:34 UTC, merged

2020-10-17 09:35 UTC, kwzrd commented
Since this is somewhat critical I decided to merge it even with an unresolved comment from @Numerlor. It only applies to code style and can be addressed separately if necessary. Feel free to continue the conversation.