Voice Gate: User activity blocks
python-discord/bot pull request #1265
Opened 2020-10-31 16:17 UTC by jb3

This PR introduces a new check for the voice gate to ensure that a users activity comes from a larger period of time rather than a burst all at once. This should deter spammers.

The way that the check works is that user activity is chunked up into 10 minute blocks which are then counted.

For example:
```
[16:05] User A: Hello!
[16:06] User A: Hello world!
```

This is one activity block because it all happened within the 16:00-16:10 block.

```
[16:05] User B: Hello!
[16:15] User B: Hello world!
```

This is two activity blocks because they fall into the 16:00-16:10 block and then 16:10-16:20 block.

This will all be described in the voice gate channel to help users understand the system.

The current threshold is more of a stab in the dark than the message threshold which is based on actual data, but looking at users we have voice banned it would certainly deter some of them.

2020-10-31 20:19 UTC, kwzrd reviewed
Only style nitpicks sorry. :disappointed: 

Is this ready on the side of Metricity?

2020-10-31 20:19 UTC, kwzrd commented on bot/exts/moderation/voice_gate.py
> +        - You must have been active for over a certain number of 10-minute blocks.
The other list items above don't end with a dot.

2020-10-31 20:19 UTC, kwzrd commented on bot/exts/moderation/voice_gate.py
> +    "activity_blocks": f"have been active for less than {GateConf.minimum_activity_blocks} ten-minute blocks"
Keeping the trailing comma is nice.

2020-10-31 20:19 UTC, kwzrd commented on config-default.yml
> +    minimum_activity_blocks: 3 # Number of 10 minute blocks during which a user must have been active
Although it's not Python code the rest of the config file still uses two spaces before the hash.

2020-10-31 20:33 UTC, kwzrd commented on bot/exts/moderation/voice_gate.py
> +    "activity_blocks": f"have been active for less than {GateConf.minimum_activity_blocks} ten-minute blocks"
Should this be "fewer than"? I don't know lol.

2020-10-31 20:36 UTC, kwzrd requested changes

2020-10-31 20:36 UTC, kwzrd commented on bot/exts/moderation/voice_gate.py
> +            "activity_blocks": data["activity_blocks"] < GateConf.activity_blocks
The attr is named `minimum_activity_blocks` not `activity_blocks`, sorry I missed this the first time.

2020-11-01 02:26 UTC, jb3 commented
The Metricity PR on site has been merged, so the data is there if you run site locally. There should be some stuff bootstrapped in the PostgreSQL init script with Docker Compose which means that the metricity_data endpoint works.

2020-11-01 13:03 UTC, kwzrd requested changes
Okay, there's a bug in the initial implementation. When site returns a 404, the code constructs an error embed for the user, and accidentally passes a tuple into the description field (see the comma at the end of `L63`).

https://github.com/python-discord/bot/blob/c8c58b7283d201a3efb0524b11591b6ed7e4f3c0/bot/exts/moderation/voice_gate.py#L57-L66

This embed then fails to send:

![image](https://user-images.githubusercontent.com/44734341/97802657-2c827380-1c45-11eb-8d4e-7739749323e8.png)

Let's remove the culprit comma as part of this PR please.

---

Now for this feature, the code looks fine and I tested it locally, though there were a few steps I had to take that I will explain here so that my methodology can be vibe checked.

Initially, I was running into the issue that the request to site was failing because the 'metricity' database did not exist. @jb3 advised me to exec into my postgres container and run the [boostrap query](https://github.com/python-discord/site/blob/master/postgres/init.sql) to create the database. This worked and solved the issue, but when we run the [total message blocks query](https://github.com/python-discord/site/blob/14d3a7e3cc1b6cc1f25d7d790b42042448383982/pydis_site/apps/api/models/bot/metricity.py#L49), it fails because the bootstrap does not create the `created_at` column:

```sql
...
SELECT
    (floor((extract('epoch' from created_at) / %s )) * %s) AS interval
FROM messages
...
```

I added this column to the create query, added myself to `users`, and inserted a message so my table now looked like this:

```
metricity=# SELECT * FROM messages;
 id  |     author_id      | is_deleted |         created_at         
-----+--------------------+------------+----------------------------
 123 | 144912469071101952 | f          | 2020-11-01 12:39:21.364375
(1 row)
```

This allows the blocks query to execute and everything else works fine. I commented out the other requirements (apart from message blocks) and reduced the required blocks to `2` in my config.

Then, I get denied when I run `!voiceverify`:

![image](https://user-images.githubusercontent.com/44734341/97803986-2ee8cb80-1c4d-11eb-8c42-54532c13453b.png)

Adding one row to `messages` with a timestamp pushed into the next block then allows me to pass the gate:

```
metricity=# SELECT * FROM messages;
 id  |     author_id      | is_deleted |         created_at         
-----+--------------------+------------+----------------------------
 123 | 144912469071101952 | f          | 2020-11-01 12:39:21.364375
 124 | 144912469071101952 | f          | 2020-11-01 12:41:21.364375
(2 rows)
```

![image](https://user-images.githubusercontent.com/44734341/97803292-85540b00-1c49-11eb-8f71-e44c576ba327.png)

So all in all this seems fine but it may be a good idea to add the `created_at` column to the bootstrap script (although that's in a separate repo). I did not check the site-side implementation much because that was already merged as part of a different PR. I also linked the site PR in your description for the convenience of other reviewers.

This is basically an approval but we should fix the tuple bug explained at the top.

2020-11-01 13:54 UTC, jb3 commented
Comma has been fixed in 399f286a157b21e860f606b4f4fed11bb29490f2. That column should indeed be added to the bootstrap script.

2020-11-01 15:34 UTC, kwzrd commented
@jb3 You added more commas, but the one that was there should have been removed instead. We want to build a string, the trailing comma was making it into a 1-tuple.

2020-11-01 15:48 UTC, kwzrd approved these changes
Looks full LGTM to me.

2020-11-01 19:22 UTC, Den4200 approved these changes
Looks good to me.

2020-11-01 19:22 UTC, merged