Parse URL and match domain name in filtering to avoid false positives
python-discord/bot pull request #1275
Opened 2020-11-07 18:10 UTC by ks129

Fixes #1260 

Before bot just used `in` check to find blacklisted domains, but this resulted false positives like is showed in linked issue. Now this find all URLs and parse them with `urllib` parser, then get domain name and check it against blacklist.

2020-11-16 18:27 UTC, MarkKoz requested changes
This isn't too accurate because not all URLs posted by users will include the HTTP scheme. Unfortunately, this will cause problems with urllib even if the URL regex is adjusted:

> Following the syntax specifications in RFC 1808, urlparse recognizes a netloc only if it is properly introduced by ‘//’. Otherwise the input is presumed to be a relative URL and thus to start with a path component.

Furthermore, the `netloc` may include a port and/or a subdomain e.g. `www.cwi.nl:80`. Some filters may need to match only on specific subdomains while others will need to match all subdomains. Adding a separate filter for each possible subdomain is infeasible, so the code needs to somehow account for this.

2020-11-21 07:41 UTC, ks129 commented
@MarkKoz #1276 this issue is for new filter that handles subdomains too, not only exact matches.

2020-11-24 08:27 UTC, MarkKoz commented
Though I think that issue could be addressed together with this one, even if set aside, my other points still need to be addressed. Someone could easily spoof the filter by omitting the scheme or specifying a port.

2020-12-04 07:34 UTC, ks129 commented
Leaving this to somebody smarter 😅

2020-12-04 07:35 UTC, Akarys42 commented
Reopening this PR in order to keep the work already done. If somebody wants to take over, feel free to do so!

2020-12-04 08:16 UTC, closed without merging