Add Branding Manager, add GitHub token
python-discord/bot pull request #1289
Opened 2020-11-17 16:46 UTC by ks129

GH token got approved in #meta, branding manager move in #dev-contrib

Added GH token from env variable `GITHUB_TOKEN`. Branding manager and PEPs use this now.

Moved branding manager from SeasonalBot (Cobra) to Python.

2020-12-31 06:57 UTC, Xithrius approved these changes
You've done an absolutely great job of seamlessly transferring this feature from [sir-lancebot](<https://github.com/python-discord/sir-lancebot>) to this bot. 

I've reviewed this as thoroughly as I could and I didn't find any conflicts or dead functions/methods/classes.

After the conflicts are resolved, this PR should be good to go.

2021-01-02 22:30 UTC, Den4200 commented
Could you please resolve these conflicts @ks129?

2021-01-03 08:05 UTC, ks129 commented
@Den4200 Conflicts resolved.

2021-01-05 20:22 UTC, MarkKoz requested changes
I'd like to see `seasons.py`, `branding.py`, and the feature-specific constants all under one sub-package.

2021-01-06 04:23 UTC, Den4200 submitted a review, later dismissed

2021-01-06 04:23 UTC, Den4200 commented on bot/errors.py
> +    pass
The `pass` here can simply be removed.
```suggestion
```

2021-01-13 20:11 UTC, MarkKoz requested changes
I think it's a little overkill to define an error module for a single error, but it's honestly fine so don't worry about changing it.

2021-01-13 20:11 UTC, MarkKoz commented on bot/exts/backend/branding/_cog.py
> +        self._startup_task = self.bot.loop.create_task(self._initial_start_daemon())
The daemon and startup tasks both need to be cancelled when the cog unloads.

2021-01-18 23:52 UTC, MarkKoz approved these changes

2021-01-19 00:00 UTC, merged