Fix #1371 error via adding errors.
python-discord/bot pull request #1401
Opened 2021-02-05 18:15 UTC by Senjan21

This PR aims to fix #1371 via raising a new error if user being infracted is not a bot and handling it within error handler.

2021-02-06 16:06 UTC, Akarys42 requested changes
Doesn't work, sir

2021-02-06 16:06 UTC, Akarys42 commented on bot/exts/backend/error_handler.py
> +                await ctx.send(f"Cannot infract that user. {e.original.reason}")
Getting
```py
bot_1       | Traceback (most recent call last):
bot_1       |   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
bot_1       |     await coro(*args, **kwargs)
bot_1       |   File "/bot/bot/exts/backend/error_handler.py", line 86, in on_command_error
bot_1       |     await ctx.send(f"Cannot infract that user. {e.original.reason}")
bot_1       | AttributeError: 'InvalidInfractedUser' object has no attribute 'reason'
```

2021-02-06 17:11 UTC, Senjan21 commented on bot/exts/backend/error_handler.py
> +                await ctx.send(f"Cannot infract that user. {e.original.reason}")
Hello, this error is no more.

2021-02-09 08:52 UTC, kosayoda approved these changes
:+1: Tested locally. Error reply could use a :x:, but it isn't important.

2021-02-10 17:58 UTC, Akarys42 approved these changes

2021-02-10 18:01 UTC, merged