Helpful Startup Errors
python-discord/bot pull request #1436
Opened 2021-02-25 10:08 UTC by HassanAbouelela

# Description
One of the biggest hurdles that people face when setting up the bot, is the lack of helpful information when things go wrong. From redis, to the API, plenty can go wrong, and it requires experience to read the traceback and figure out why.

# Inspiration
This PR aims to take a step in fixing that, by offering more descriptive errors on startup. This is inspired by #1385, but only covers a portion of the proposed changes.

# Implemntation
This PR does two things:
1. It logs a message for redis and API errors, so we don't keep getting confused people asking why they got a 100 line traceback when they hit run.
2. It adds retries to site connection, so it solves the problem of the bot trying to connect to the site before it warms up in docker. (Right now that is at 3 attempts with 5 seconds between each).

2021-02-25 10:32 UTC, Akarys42 requested changes
This seems to be working fine, although I have some comments to make

2021-02-25 10:32 UTC, Akarys42 commented on bot/bot.py
> +        super()
I believe you meant
```suggestion
        super().__init__()
```

2021-02-25 10:32 UTC, Akarys42 commented on bot/bot.py
> +                    raise e
Nitpicky, but it can just be
```suggestion
                    raise
```

2021-02-25 10:32 UTC, Akarys42 commented on bot/__main__.py
> +    log.fatal(message)
This should exit with a non-zero code

2021-02-25 10:32 UTC, Akarys42 commented on bot/__main__.py
> +    if type(e.exception) in [aiohttp.ClientConnectorError, aiohttp.ServerDisconnectedError]:
This should be an `isinstance` check ~~and it should be a tuple, not a list :P~~

2021-02-26 16:22 UTC, Akarys42 approved these changes
LGTM, thanks!

2021-02-26 16:33 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-02-26 16:43 UTC, merged