Unescape html escape characters in reddit text and titles
python-discord/bot pull request #1441
Opened 2021-03-01 15:06 UTC by asleep-cult

Use `html.unescape` to replace html escape characters with their Unicode equivalent in reddit text and titles.
Examples:
<img width="307" alt="Capture" src="https://user-images.githubusercontent.com/65962434/109515444-12cb2e80-7a75-11eb-9cc0-3d5915fdc4b0.PNG">
<img width="297" alt="Capture" src="https://user-images.githubusercontent.com/65962434/109515240-de577280-7a74-11eb-84c1-8afb5891e60b.PNG">

2021-03-01 16:30 UTC, Shivansh-007 requested changes
Nitpick

2021-03-01 16:30 UTC, Shivansh-007 commented on bot/exts/info/reddit.py
> +import html
We don’t really need the full library here. 
```suggestion
from html import unescape
```

2021-03-01 17:02 UTC, Shivansh-007 approved these changes
Thanks! Looks Good To Me!

2021-03-05 18:42 UTC, ChrisLovering requested changes
We usually recommend that you raise issues before raising a PR directly to the repo, as it's possible the core dev team will have opinions.

As far this change, we are currently porting this over to [Sir Lancebot](https://github.com/python-discord/sir-lancebot) with https://github.com/python-discord/sir-lancebot/issues/530 and https://github.com/python-discord/sir-lancebot/pull/569

If we decide that we want these changes in the meantime, my comments are below.

2021-03-05 18:42 UTC, ChrisLovering commented on bot/exts/info/reddit.py
> +            title = textwrap.shorten(title, width=64, placeholder="...")
Could we have this and the line above in a single assignment?
```suggestion
            title = textwrap.shorten(
                unescape(data["title"]),
                width=64,
                placeholder="..."
            )
```

2021-03-05 18:42 UTC, ChrisLovering commented on bot/exts/info/reddit.py
>              if text:
The line above could be moved into this if statement as a walrus operator
```suggestion
            if text := unescape(data["selftext"]):
```

2021-03-28 17:55 UTC, Xithrius commented
@asleep-cult Will you be continuing this PR?

2021-05-05 10:44 UTC, ChrisLovering approved these changes

2021-05-05 10:47 UTC, vcokltfre approved these changes

2021-05-05 10:49 UTC, Xithrius commented
We'll merge this for the time being, should be fixed in Reddit migration to Sir-Lancebot.

2021-05-05 10:49 UTC, merged