Use JSON logging in production
python-discord/bot pull request #1449
Opened 2021-03-06 12:01 UTC by jb3

JSON logging allows for greater filtering with our log aggregator, Loki.

This PR introduces JSON logging when debug mode is set to false (i.e. the bot is running in production).

<img width="1037" alt="Screenshot 2021-03-06 at 12 01 02" src="https://user-images.githubusercontent.com/20439493/110206078-a0db5680-7e73-11eb-8188-80e8616222a1.png">

2021-03-06 12:13 UTC, Shivansh-007 approved these changes
Tada, tested locally!

2021-03-06 13:05 UTC, HassanAbouelela requested changes
Interestingly, some things slip through the JSON formatting (probably because they aren't logged, just straight up warnings/errors, such as not having `python-Levenshtein` installed), but that's not really important for the bot, just something you'd have to account for on the Loki end.

2021-03-06 13:07 UTC, jb3 commented on Pipfile
> +python-json-logger = "*"
Addressed in fe5e2ab947a8c2123f2856db24d9c6e978adec9d

2021-03-06 13:08 UTC, HassanAbouelela approved these changes

2021-03-06 13:08 UTC, jb3 commented
Hold on, need a Pipfile.lock bump

2021-03-06 13:17 UTC, HassanAbouelela approved these changes
One more approval for old time's sake.

2021-03-06 13:19 UTC, merged

2021-03-08 17:55 UTC, HassanAbouelela commented
This PR is being reverted due to an internal decision. See discussion [here](https://discord.com/channels/267624335836053506/411200599653351425/818541370083377152).