Limit nominate command channels
python-discord/bot pull request #1479
Opened 2021-03-21 14:04 UTC by wookie184

This limits the `!nominate` command to the nominations channel, adds a force nominate command so mods can override that, and also adds the `moderators` category to the config as a moderation category, so `nomination-discussion` and any new channels added in the future can have moderation commands run in them.

2021-03-22 16:51 UTC, Akarys42 requested changes
Just one small thing!

2021-03-22 16:51 UTC, Akarys42 commented on config-default.yml
> -        mod_appeals:        &MOD_APPEALS    808790025688711198
Since those channels have been from here, they also need to be removed from `bot/constants.py`.

2021-03-22 16:57 UTC, wookie184 commented
I don't think the ones I removed were in the constants.py (unless I'm missing something)

2021-04-01 20:15 UTC, MarkKoz commented
Why make a separate command instead of allowing the original one to work everywhere for moderators?

2021-04-02 10:48 UTC, wookie184 commented
> 
> 
> Why make a separate command instead of allowing the original one to work everywhere for moderators?

To discourage moderators from running the nominate command in channels other than the `nominations` channel, for example if they clicked on the wrong channel or didn't realise they should only use the `nominations` channel, while still allowing them to bypass that if necessary. Granted theses cases would be rare, but I don't think there's much harm in adding a separate command.

2021-04-04 18:48 UTC, Akarys42 approved these changes

2021-04-04 18:49 UTC, Akarys42 approved these changes
you can do it review bot

2021-04-04 18:49 UTC, Xithrius approved these changes
Looks good to my eyes

2021-04-04 18:50 UTC, Akarys42 approved these changes
I don't like you review bot

2021-04-04 18:51 UTC, merged