Create str-join.md
python-discord/bot pull request #1520
Opened 2021-04-12 15:21 UTC by SavagePastaMan

Create a tag to showcase `str.join`

2021-04-12 15:27 UTC, Akarys42 commented
Hey @SavagePastaMan, can you please add a bit more content to the PR body? right now it isn't saying much about the PR either how it looks inside the server. Also, don't forget to lint!

2021-04-12 15:31 UTC, SavagePastaMan commented
i'm just using the github editor :pensive:. I also don't have a local instance of the bot so I can't get screenshots 😬.

2021-04-12 22:54 UTC, ChrisLovering approved these changes

2021-04-15 14:56 UTC, mbaruh requested changes
I'd keep it as short as possible, and also maybe a bit less opinionated.

2021-04-15 14:56 UTC, mbaruh commented on bot/resources/tags/str-join.md
> +Suppose you want to nicely display a list (or some other iterable). The naive solution would be something like this.
```suggestion
If you want to display a list (or some other iterable), you can write:
```

2021-04-15 14:56 UTC, mbaruh commented on bot/resources/tags/str-join.md
> +However, this solution is flawed. The separator is still added to the last element, and it is slow.
```suggestion
However, the separator is still added to the last element, and it is relatively slow.
```

2021-04-15 14:56 UTC, mbaruh commented on bot/resources/tags/str-join.md
> +The better solution is to use `str.join`.
```suggestion
A better solution is to use `str.join`.
```

2021-04-15 14:56 UTC, mbaruh commented on bot/resources/tags/str-join.md
> +This solution is much simpler, faster, and solves the problem of the extra separator. An important thing to note is that you can only `str.join` strings. For a list of ints,
```suggestion
An important thing to note is that you can only `str.join` strings. For a list of ints,
```

2021-05-03 23:13 UTC, Xithrius commented
Author will not be able to complete this PR, so I'll be taking over.

2021-05-04 08:39 UTC, mbaruh approved these changes

2021-05-04 08:41 UTC, Akarys42 approved these changes

2021-05-04 08:42 UTC, merged