Added blocking tag
python-discord/bot pull request #1558
Opened 2021-05-01 17:16 UTC by doublevcodes

This PR adds a new tag to `resources/tags` which explains how when coding asynchronously you should limit the amount of blocking calls you make.

### Closes:
#1410

2021-05-01 22:25 UTC, Xithrius commented
Continuation of https://github.com/python-discord/bot/pull/1410.

2021-05-02 16:39 UTC, vcokltfre commented on bot/resources/tags/blocking.md
> +An asynchronous programme utilises the `async` and `await` keywords. An asynchronous programme pauses what it's doing and does something else whilst it waits for some third-party service to complete
Pydis primarily uses British spelling for things, so that doesn't really make sense

2021-05-02 17:28 UTC, MarkKoz commented on bot/resources/tags/blocking.md
> +An asynchronous programme utilises the `async` and `await` keywords. An asynchronous programme pauses what it's doing and does something else whilst it waits for some third-party service to complete
It doesn't really matter as long as its consistent across the body of the text. How the author spells it is how it should be accepted. That being said, I tend to not see `programme` used in the computing sense, only for something like `television programme`.

2021-05-02 19:00 UTC, doublevcodes commented on bot/resources/tags/blocking.md
> +An asynchronous programme utilises the `async` and `await` keywords. An asynchronous programme pauses what it's doing and does something else whilst it waits for some third-party service to complete
Ah ok then, I'll switch to program, but I'll keep my spelling of utilises

2021-05-16 18:24 UTC, Xithrius commented
@doublevcodes will you be applying the changes that have been stated sometime soon?

Thanks.

2021-05-16 19:27 UTC, vcokltfre requested changes

2021-05-16 19:27 UTC, vcokltfre commented on bot/resources/tags/blocking.md
> +Imagine that you're coding a Discord bot and every time somebody uses a command, you need to get some information from a database. But there's a catch: the database servers are acting up today and ta
> If you did **not**

and then later on

> your whole bot will

This should be in the same tense, either past or present, but not both

2021-05-16 19:28 UTC, vcokltfre commented on bot/resources/tags/blocking.md
> +Imagine that you're coding a Discord bot and every time somebody uses a command, you need to get some information from a database. But there's a catch: the database servers are acting up today and ta
The rest of the tag seems to be present tense, so I'd recommend changing `if you did` to `if you do`

2021-05-16 19:32 UTC, vcokltfre approved these changes
Looks good!

2021-05-16 22:03 UTC, merged