feat: add async-await tag
python-discord/bot pull request #1594
Opened 2021-05-17 18:14 UTC by vcokltfre

Async await tag as approved in #1585 

![image](https://user-images.githubusercontent.com/16879430/118536715-f5d4fc00-b743-11eb-8ef3-b902480cdbf7.png)

2021-05-17 18:26 UTC, ToxicKidz requested changes
Hey, this is a good tag, just a couple of suggestions. Is it worth mentioning the use of `asyncio.run` as well?

2021-05-17 18:26 UTC, ToxicKidz commented on bot/resources/tags/async-await.md
> +To run the top level async function from outside of the even loop we can get an event loop from `asyncio`, and then use that loop to run the function:
```suggestion
To run the top level async function from outside of the event loop we can get an event loop from `asyncio`, and then use that loop to run the function:
```

2021-05-17 18:26 UTC, ToxicKidz commented on bot/resources/tags/async-await.md
> +Note that in the `run_until_complete()` where we appear to be calling `main()`, this does not execute the code in `main`, rather it returns a `Coroutine` object which is then handled and run by the e
```suggestion
Note that in the `run_until_complete()` where we appear to be calling `main()`, this does not execute the code in `main`, rather it returns a `coroutine` object which is then handled and run by the event loop via `run_until_complete()`.
```

2021-05-17 18:26 UTC, ToxicKidz commented on bot/resources/tags/async-await.md
> +To learn more about asyncio and it's use, see the [asyncio documentation](https://docs.python.org/3/library/asyncio.html).
```suggestion
To learn more about asyncio and its use, see the [asyncio documentation](https://docs.python.org/3/library/asyncio.html).
```

2021-06-04 12:27 UTC, Xithrius approved these changes
Yes.

2021-06-04 13:31 UTC, ToxicKidz approved these changes
:shipit:

2021-06-04 13:36 UTC, merged