Enforce one help channel per user
python-discord/bot pull request #1608
Opened 2021-05-21 23:27 UTC by swfarnsworth

This PR removes the cool down functionality from the help channel cooldown role, and instead applies the role when their help channel opens and removes it exactly when that channel closes, thereby ensuring that a given user is never the claimant of more than one channel.

If you test this functionality, please list which cases you tried.

2021-05-24 17:50 UTC, wookie184 commented
Have played around with it a bit and it seems to work fine. My only worry is that removing the timed cooldown creates a potential for trolls to quickly open and close their channel to mess with the system, I think that was one of the reasons for having a cooldown. On the other hand, being able to simplify the system is nice, and the amount of harm somebody could cause is likely pretty low and we would notice/deal with it pretty quickly.

To clarify, that would still involve limiting the help channels to one per person, but on top of that there would be a short cooldown (e.g. 5 minutes) to prevent abuse. Thoughts?

2021-05-24 18:01 UTC, swfarnsworth commented
@wookie184 I don't think that concern was raised during the meeting where we green-lit this change.

I'm hesitant to have the "channel is closed and five minutes" cooldown as it re-introduces some of the complexity that this seeks to eliminate. I have also at times closed help sessions that have been overrun by trolls and instructed the claimant to open a new session, and I wouldn't want to lose the option to do that without penalizing the claimant.

2021-05-24 19:07 UTC, wookie184 approved these changes
My bad, I forgot that the role was already removed. In that case this isn't a change of behaviour in that regard so it's fine. This looks good to me, have tested and the role is added and removed correctly, with command `!close` and natural close.

You could add log messages for when the role is added or removed, as was in `add_cooldown_role` and `remove_cooldown_role` previously

2021-05-25 02:43 UTC, MarkKoz requested changes
I'm not too concerned about `get_role` failing, but `add_roles` should have some exception handling. Failing to change the role isn't a critical failure; it shouldn't leave the system in an invalid/broken state. Some of the functions you removed were taking care of the error handling. I don't see why you can't just leave them in and keep using them.

2021-05-31 04:03 UTC, MarkKoz requested changes

2021-05-31 04:03 UTC, MarkKoz commented on bot/exts/help_channels/_cog.py
> +        cooldown_role = self.bot.get_guild(constants.Guild.id).get_role(constants.Roles.help_cooldown)
This line can be put into the function to reduce code redundancy.

2021-05-31 22:17 UTC, MarkKoz approved these changes

2021-05-31 22:17 UTC, merged