Prevent one from using the `!echo` command for a channel in which one can't speak
python-discord/bot pull request #1656
Opened 2021-06-22 21:44 UTC by swfarnsworth

Changes the `!echo` command so that if someone attempts to echo to a channel in which they don't have send message permissions, the message is not relayed. Though that has never happened in the history of Python Discord.

2021-06-22 22:09 UTC, jb3 approved these changes
:shipit::shipit::shipit::shipit::shipit:

2021-06-22 22:10 UTC, lemonsaurus requested changes

2021-06-22 22:10 UTC, lemonsaurus commented on bot/exts/utils/bot.py
> +            await ctx.send('You don\'t have permission to speak in that channel.')
```suggestion
            await ctx.send("You don't have permission to speak in that channel.")
```
What sort of escapism is this? 🦖 🦖🦖

2021-06-22 22:15 UTC, ToxicKidz approved these changes

2021-06-22 22:17 UTC, Den4200 approved these changes

2021-06-23 08:15 UTC, lemonsaurus approved these changes

2021-06-23 08:15 UTC, merged