Unpin all messages when help channel goes dormant
python-discord/bot pull request #1936
Opened 2021-11-05 08:05 UTC by dementati

2021-11-05 17:42 UTC, MarkKoz commented
If they're unpinned when the channel becomes available, then why even bother unpinning when it goes dormant?

> This allows us to get rid of the message cache with no known disadvantages.

Getting pinned messages requires an API call to Discord. With the cache, this is avoided. That is basically the only advantage. That being said, this sort of optimisation is not necessary; it was nice to have but it's not worth keeping if it's causing consistency issues.

2021-11-07 06:46 UTC, dementati commented
> If they're unpinned when the channel becomes available, then why even bother unpinning when it goes dormant?

Apparently, it's the API itself that bugs out occasionally, and making two passes will decrease the likelihood that there are pins remaining by the time the channel becomes available.

> Getting pinned messages requires an API call to Discord. With the cache, this is avoided. That is basically the only advantage.

That is true.

> it was nice to have but it's not worth keeping if it's causing consistency issues.

As stated above, it's allegedly the API and not the cache that caused the issue. I just prefer the solution in this PR because it reduces code complexity.

2021-12-01 22:21 UTC, Bluenix2 approved these changes
Perfect, works much better than the previous behaviour! Another bug squashed..
![image](https://emojis.slackmojis.com/emojis/images/1616835194/24413/fly-swatter.gif?1616835194)

2021-12-03 01:02 UTC, onerandomusername requested changes

2021-12-03 01:02 UTC, onerandomusername commented on bot/exts/help_channels/_message.py
>      """Pin an initial question `message` and store it in a cache."""
No longer storing to a cache.

2022-03-12 21:43 UTC, MarkKoz requested changes

2022-03-12 21:43 UTC, MarkKoz commented on bot/exts/help_channels/_message.py
>      """Pin an initial question `message` and store it in a cache."""
```suggestion
    """Pin an initial question `message`."""
```

2022-03-12 21:43 UTC, MarkKoz commented on bot/exts/help_channels/_message.py
>      """Unpin the initial question message sent in `channel`."""
```suggestion
    """Unpin all messages sent in `channel`."""
```

2022-03-12 21:54 UTC, MarkKoz reviewed
This will allow a `discord.Message` to be passed to `pin_wrapper` instead of a message ID. Thus, the wrapper will be able to call the `discord.Message.pin` and `discord.Message.unpin` functions rather than using the undocumented methods on `HTTPClient`. Would you mind updating the wrapper function too @dementati?

2022-05-27 21:51 UTC, Xithrius commented
@dementati What's your status on this PR?

2022-06-07 19:49 UTC, MarkKoz approved these changes

2022-06-07 21:11 UTC, ChrisLovering approved these changes

2022-06-07 21:12 UTC, merged