Sync Help Cooldown role with help channel claimants
python-discord/bot pull request #1940
Opened 2021-11-07 09:50 UTC by dementati

Every hour, retrieve all channel claimants from Redis cache,
get all members who currently have the Help Cooldown role,
then remove the role from any such member who is not a
channel claimant as per the cache.

2021-12-02 19:30 UTC, onerandomusername commented on tests/helpers.py
> +class MockRedisCache(unittest.mock.MagicMock):
nit: this should be a NonCallableMagicMock

If an instance of RedisCache can not be called, this shouldn't be callable either.

2021-12-16 20:06 UTC, mbaruh requested changes

2021-12-16 20:06 UTC, mbaruh commented on bot/exts/help_channels/_cog.py
> +        nonclaimants_with_role = [member for member in help_cooldown.members if member.id not in claimants]
Do you think it might be worth converting claimants into a set?

2021-12-16 20:29 UTC, Bluenix2 approved these changes
Works like a charm! Thanks, this is great.

2021-12-25 19:13 UTC, MarkKoz commented on bot/exts/help_channels/_cog.py
> +        await self.bot.wait_until_ready()
Why not put this directly in `sync_cooldown_roles`?

2022-05-27 21:54 UTC, Xithrius commented
@dementati This PR seems fairly close to being done. Will you be available sometime soon to complete this?

2022-05-28 00:38 UTC, onerandomusername commented
Per recent policy changes this should no longer use the redis cache for persistent data.

See https://canary.discord.com/channels/267624335836053506/635950537262759947/955991104208138290

2023-01-30 07:12 UTC, MarkKoz commented
Hey, I'm closing this PR since it's had no activity and is outdated due to migrating to using a forum for the help system.

2023-01-30 07:12 UTC, closed without merging