Ensure claimant cache is populated on help channel init
python-discord/bot pull request #2078
Opened 2022-02-09 12:58 UTC by ChrisLovering

These changes ensure that for every help channel in use, a claimant is present in the redis cache. This is to avoid an issue caused when a user tries to close a channel, but the cache is empty so the author check fails.

This also cancels a help channel claim if we hit a discord 500 error while moving the channel.

2022-02-14 02:06 UTC, GDWR approved these changes

2022-02-20 20:15 UTC, ToxicKidz requested changes
Looks good, one bug in `ensure_cached_claimant`.

2022-02-20 20:15 UTC, ToxicKidz commented on bot/exts/help_channels/_channel.py
> +            await _caches.claimants.set(channel.id, user_id)
This should be cast to `int`.
```suggestion
            await _caches.claimants.set(channel.id, int(user_id))
```

2022-02-20 20:17 UTC, ChrisLovering commented on bot/exts/help_channels/_channel.py
> +            await _caches.claimants.set(channel.id, user_id)
Nice catch :D

2022-02-20 20:17 UTC, ChrisLovering commented
Will squash before merging

2022-02-20 20:27 UTC, ToxicKidz approved these changes
Works well :shipit:

2022-02-20 21:45 UTC, merged