Update to canonical PEP URLs
python-discord/bot pull request #2123
Opened 2022-03-31 09:44 UTC by hugovk

With the recent implementation of [PEP 676](https://peps.python.org/pep-0676/) the canonical URL for PEPs has changed from, for example:

https://www.python.org/dev/peps/pep-0008/

to:

https://peps.python.org/pep-0008/

Redirects are in place so the old links still work, but let's update to use the new canonical form.

See also:

* [bpo-47126](https://bugs.python.org/issue47126) / https://github.com/python/cpython/pull/32124
* https://github.com/python/devguide/pull/822
* https://github.com/sphinx-doc/sphinx/pull/10267

---

Also the RSS feed:

```python
PEPS_RSS_URL = "https://www.python.org/dev/peps/peps.rss/"
```

Redirects to `https://peps.python.org/peps.rss/` with trailing slash which is a 404.

`https://peps.python.org/peps.rss` without trailing slash works, so let's use this. 

(I've also filed https://github.com/python/peps/issues/2493, because we should keep that old redirect working too.)

2022-03-31 11:30 UTC, wookie184 approved these changes
Thanks for the PR!

2022-03-31 13:53 UTC, onerandomusername requested changes

2022-03-31 14:05 UTC, wookie184 commented on bot/exts/info/pep.py
> +            url="https://peps.python.org/"
They are the same page, so it doesn't really matter.

2022-04-03 18:07 UTC, ChrisLovering approved these changes

2022-04-03 18:09 UTC, merged