Added an option to use 0s as an argument
python-discord/bot pull request #2134
Opened 2022-04-18 23:28 UTC by novialriptide

I'm not 100% sure if this was the solution you guys were looking for, but it works.

![image](https://user-images.githubusercontent.com/35881688/163892631-0958eea8-abb3-4c30-9124-8ba9b32c06eb.png)

Fix: https://github.com/python-discord/bot/issues/2132

2022-04-18 23:54 UTC, mbaruh requested changes

2022-04-18 23:54 UTC, mbaruh commented on bot/exts/moderation/slowmode.py
> +            delay = relativedelta(seconds=0)
This isn't necessarily the expected behavior. This behavior means that any invalid duration will reset the slowmode, while the behavior outlined in the issue is to just make an exception for "0s".

You could check for the value of the string, or you could make use of the converters and make the delay a union of `DuraitonDelta` and a `Literal["0s"]`

2022-04-19 00:26 UTC, novialriptide commented
![image](https://user-images.githubusercontent.com/35881688/163897088-63e02160-d3a8-4620-968e-837acf96fc34.png)
Updated.

2022-04-19 01:31 UTC, minalike commented
Can a core dev comment/confirm: I just realized the `!defcon threshold` command supports passing just `0` (without the `s`). Could we add support for `0` to this command as well?

2022-04-19 09:48 UTC, ChrisLovering commented
For this, I would suggest instead of using literal, we do the same as what defcon has. https://github.com/python-discord/bot/blob/main/bot/exts/moderation/defcon.py#L163-L178

This Unions the DurationDelta with an int, if it's an int defcon assumed it's a number of days, for this we could assume a number of seconds and then use that

2022-04-19 12:09 UTC, mbaruh commented
> For this, I would suggest instead of using literal, we do the same as what defcon has. https://github.com/python-discord/bot/blob/main/bot/exts/moderation/defcon.py#L163-L178
> 
> This Unions the DurationDelta with an int, if it's an int defcon assumed it's a number of days, for this we could assume a number of seconds and then use that

I don't mind, but the reason for this PR is that people are trying to use "0s" specifically

2022-04-19 12:15 UTC, ChrisLovering commented
> > For this, I would suggest instead of using literal, we do the same as what defcon has. https://github.com/python-discord/bot/blob/main/bot/exts/moderation/defcon.py#L163-L178
> > This Unions the DurationDelta with an int, if it's an int defcon assumed it's a number of days, for this we could assume a number of seconds and then use that
> 
> I don't mind, but the reason for this PR is that people are trying to use "0s" specifically

Is there a specific reason that the duration delta doesn't all 0s as a valid duration? Would be nicer to solve this issue there then.

2022-04-19 12:31 UTC, mbaruh commented
@ChrisLovering durationdelta is used in all time related commands, including infractions, reminders, and clean. A 0 duration makes no sense there and will most likely break a few things.

2022-04-19 12:43 UTC, ChrisLovering commented
> @ChrisLovering durationdelta is used in all time related commands, including infractions, reminders, and clean. A 0 duration makes no sense there and will most likely break a few things.

Ah good point, this is probably best then, the alternative is to make a new convertor that accepts 0 delta durations.

2022-04-19 14:37 UTC, ChrisLovering requested changes
Can't test the code right now, so only have a styling request.

2022-04-19 14:37 UTC, ChrisLovering commented on bot/exts/moderation/slowmode.py
> +                           delay: Union[DurationDelta, Literal["0s", "0seconds"]]) -> None:
```suggestion
    async def set_slowmode(
        self,
        ctx: Context,
        channel: Optional[TextChannel],
        delay : Union[DurationDelta, Literal["0s", "0seconds"]],
    ) -> None:
```
To be consistent with how we format other function signatures in the bot

2022-04-21 20:22 UTC, mbaruh approved these changes
Looks good, thank!

2022-04-21 21:09 UTC, ChrisLovering approved these changes

2022-04-21 21:12 UTC, merged