Bump bot-core to 8.2.1 and bump other deps to latest
python-discord/bot pull request #2287
Opened 2022-10-10 20:22 UTC by ChrisLovering

From the release notes on d.py [here](https://canary.discord.com/channels/336642139381301249/381965829857738772/1006359073610010664) and [here](https://canary.discord.com/channels/336642139381301249/381965829857738772/1008772795179737230) none of the breaking changes for the commit we were on to 2.0.1 affect us.

2022-10-10 20:24 UTC, ChrisLovering commented on pyproject.toml
> +flake8-isort = "5.0.0"
Breaking change in the major version bump was to remove support for Python 3.6.
https://pypi.org/project/flake8-isort/5.0.0/

2022-10-10 20:24 UTC, ChrisLovering commented on pyproject.toml
> +pytest-cov = "4.0.0"
Breaking change in the major version bump was to remove support multiprocessing, which we don't use.
https://pypi.org/project/pytest-cov/

2022-10-10 20:24 UTC, ChrisLovering commented on pyproject.toml
> +flake8 = "5.0.4"
Breaking changes in this major version bump don't affect us

https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html

2022-10-10 20:45 UTC, mbaruh requested changes

2022-10-10 20:56 UTC, ChrisLovering commented on pyproject.toml
> +markdownify = "0.11.6"
No, and I completely ignored the commit directly above, which I left 😅.

Fixed in a forcepush.

2022-10-11 06:28 UTC, mbaruh approved these changes

2022-10-15 22:49 UTC, ionite34 approved these changes

2022-10-15 23:39 UTC, merged