Make snekbox 3.11 stable default, with 3.10 as an option
python-discord/bot pull request #2324
Opened 2022-11-13 14:41 UTC by ChrisLovering

2022-11-13 15:49 UTC, HassanAbouelela approved these changes
I had just updated my config chris!

2022-11-14 11:27 UTC, mbaruh requested changes
I'm not convinced we should keep 3.10 as an option, if 3.11 is stable and has wheels for all of the libraries we use. I'm ok with removing the button without removing the code for switching between versions.

2022-11-14 11:27 UTC, mbaruh commented on tests/bot/exts/utils/test_snekbox.py
> +            constants.URLs.snekbox_310_eval_api,
I'm not sure this is the intended behavior of the test. If the default version is now 3.11 then it makes more sense to change the tests to use 3.11.

2022-11-17 17:22 UTC, mbaruh commented
> 3.11 was already deployed (and we don’t need wheels since we have gcc in the snekbox image)

yeah the bottom line is that if we can have all of the usual libraries available then I don't think we need to have 3.10 as an option. We had two versions only because we wanted to promote 3.11 before its release.

2023-03-29 17:07 UTC, ChrisLovering commented
With https://github.com/python-discord/snekbox/pull/175 around the corner, and the recent config changes, I don't think updating this PR is worth the effort.

2023-03-29 17:07 UTC, closed without merging