Add questions tag
python-discord/bot pull request #2378
Opened 2023-01-12 09:56 UTC by meatballs

Because I find myself pointing people to [Asking Good Questions](https://www.pythondiscord.com/pages/guides/pydis-guides/asking-good-questions/) regularly.

2023-01-12 14:22 UTC, CaedenPH reviewed
Just my opinion, but this seems a little bare. Perhaps some other information could be useful

2023-01-12 14:24 UTC, meatballs commented
What do you think it needs? The page it links to has comprehensive detail and I didn't want to just repeat any of that.

2023-02-01 20:36 UTC, brodycritchlow approved these changes
Don't see any point in adding anymore. The link provides enough detail. Looks good

2023-02-28 03:47 UTC, Robin5605 approved these changes
Short, concise, and links to a more detailed article. A perfect combination for tags. LGTM :+1:

2023-02-28 09:02 UTC, shtlrs requested changes

2023-02-28 09:02 UTC, shtlrs commented on bot/resources/tags/questions.md
> +**Asking Good Questions**
This needs to change to comply with the news tags slash command
#2419 is your friend

2023-02-28 10:18 UTC, HassanAbouelela commented
Blocked for further discussion, please open an issue in python-discord/meta.

2023-03-12 20:49 UTC, mbaruh commented
Staff consensus in today's meeting is that we don't want to go forward with it, largely for the same reasons we removed the old !ask tag. The link doesn't clarify what exactly is wrong with the question asked, which is very context specific, and has a high chance of being used passive-aggressively by being dumped at people (sometimes several times) with no further explanation, as we have seen with the old tag.

2023-03-12 20:49 UTC, closed without merging