Redesign infractions embed
python-discord/bot pull request #2526
Opened 2023-04-10 13:58 UTC by mbaruh

Redesigns the infractions embed to be more concise and compact.

Before:
![image](https://user-images.githubusercontent.com/18114431/230914137-d948b416-03e2-40ff-a717-b86197a4de21.png)
After:
![image](https://user-images.githubusercontent.com/18114431/230914168-ad4d2ab7-2676-43fe-8f22-ba33fe162831.png)

The new embeds has a row of symbols that are explained in the help embeds of the appropriate commands:
![image](https://user-images.githubusercontent.com/18114431/230914485-aa94f43e-dabc-4bb3-9229-2f3955b203c4.png)
I expect more symbols to be added in the future once the DB and bot can support them, such as the reason being edited, the infraction being manually pardoned (e.g due to an appeal), and the context link leading to a modmail log.

2023-04-10 14:39 UTC, ChrisLovering approved these changes

2023-04-10 14:39 UTC, ChrisLovering commented on bot/exts/moderation/infraction/management.py
> +            symbols.append("✏️")
Maybe we should have these as constants at the top of the file, used by both the SYMBOLS_GUIDE and here, so if we want to change a symbol it's just in one place

2023-04-12 14:08 UTC, wookie184 requested changes
If you timeout and then untimeout a user, it is unclear that the timeout is no longer active in the infraction listing. 

I know for active timeouts it specifically says they are active, but seeing this:
![image](https://user-images.githubusercontent.com/22353562/231483199-5876f41f-07c1-4ba7-b2c1-ae15a9c9acd4.png)

still makes me think that it is active, due to the expiry.

2023-04-13 11:37 UTC, wookie184 approved these changes
Looks great! I'll let you merge

2023-04-13 14:31 UTC, merged