Add Tag Issue Template
python-discord/bot pull request #2540
Opened 2023-04-15 05:46 UTC by HassanAbouelela

People (contribs, staff, and core-devs alike) have often been confused by where to create issues for adding new tags. Creating issues on this repository makes the most sense - issue follows implementation - but it's rarely the correct option. Tag suggestions issues are never about implementation details, but specific tag details such as: do we want this? what form do we want it in? etc.

These questions can not be discussed adequately on this repository as it's difficult to gain traction and get people seeing it. The meta repository is a much better location for it, and hence the [tag suggestion template](https://github.com/python-discord/meta/blob/main/.github/ISSUE_TEMPLATE/tag-request.yaml) exists. This is an attempt at guiding people towards it.

2023-04-15 09:29 UTC, shtlrs requested changes
Great idea, just one tiny comment.

2023-04-15 09:29 UTC, shtlrs commented on .github/ISSUE_TEMPLATE/tag-suggestion.yml
> +title: I DID NOT READ THE INSTRUCTIONS
I would suggest making it clearer, as this currently sounds like an "inside joke". (The fact that people never read the instructions, so we made this)

For example
```suggestion
title: TAG ISSUES GO TO THE META REPO, PLEASE READ THE FOLLOWING INSTRUCTIONS
```

2023-04-15 11:16 UTC, wookie184 commented
I think it would be neater to use `contact_links` here given that's what they're intended for. For examples, see https://github.com/PyCQA/flake8/issues/new/choose and https://github.com/facebook/react/issues/new/choose

2023-04-15 11:20 UTC, wookie184 commented
Also, looking at https://github.com/facebook/react/issues/new/choose it seems the option to create a blank issue is pretty hidden away. If we want to add a template for this I think we'd have to add ones for normal usage too.

2023-04-15 12:25 UTC, shtlrs commented
> I think it would be neater to use `contact_links` here given that's what they're intended for. For examples, see https://github.com/PyCQA/flake8/issues/new/choose and https://github.com/facebook/react/issues/new/choose

Nice ! I didn't know these existed.
In that case, I agree with wookie on the fact that it would look neater if we use `contact_links` for that.

2024-04-02 12:54 UTC, wookie184 commented
I'm going to close this as it's been stale for a while and I don't think it's close to merging. Given my second comment:

> Also, looking at https://github.com/facebook/react/issues/new/choose it seems the option to create a blank issue is pretty hidden away. If we want to add a template for this I think we'd have to add ones for normal usage too.

I think this would need to go along with https://github.com/python-discord/bot/issues/1599 so I'd consider this something that should be solved as part of that issue.

2024-04-02 12:54 UTC, closed without merging