Remove !close command from helpers.
python-discord/bot pull request #2548
Opened 2023-04-18 00:55 UTC by swfarnsworth

Previously, helpers could use the !close command to put inactive help channels back into circulation. This is no longer necessary now that we use threads.

I confirmed that each of these cases work correctly on my test server:
* Close the thread as the OP with no role
* Not be able to close someone else's thread as a helper
* Close someone else's thread as admin

2023-04-18 01:02 UTC, mbaruh approved these changes

2023-04-18 09:46 UTC, ChrisLovering requested changes

2023-04-18 09:46 UTC, ChrisLovering commented on bot/constants.py
> +    cmd_whitelist: list[int] = [Roles.moderators, Roles.admins]
```suggestion
    cmd_whitelist = Guild.moderation_roles
```
We should use this instead, or better yet, remove this constant entirely and just use `Guild.moderation_roles` in the cog.

2023-04-21 18:15 UTC, ChrisLovering approved these changes

2023-04-21 18:15 UTC, merged