Bump to pydis core 10
python-discord/bot pull request #2685
Opened 2023-07-19 13:40 UTC by shtlrs

> The pyproject file will be updated when the new version is released.

* Bumps pydis_core to 10.0.0
* Uses the utils already available in pydis_core instead of duplicating them here.

2023-07-25 10:20 UTC, ChrisLovering approved these changes
LGTM.

Now that bot-core can support multiple files, we should update the snekbox cog, in another PR, so that it uploads the text file outputs alongside all of the other outputs, rather than creating many pastefiles

2023-08-12 13:22 UTC, wookie184 requested changes
One nit

2023-08-12 13:22 UTC, wookie184 commented on bot/exts/moderation/dm_relay.py
> +        file = PasteFile(content=metadata+output, lexer="text")
Should have spaces around operators as per PEP 8
```suggestion
        file = PasteFile(content=metadata + output, lexer="text")
```

2023-08-15 11:08 UTC, wookie184 approved these changes

2023-08-26 10:07 UTC, merged