Support reply as a message reference for !raw [json]
python-discord/bot pull request #2864
Opened 2023-12-25 21:37 UTC by ichard26

Addresses GH-2761.

![image](https://github.com/python-discord/bot/assets/63936253/75b75839-1588-42f4-9fed-e7628f188481)

2023-12-25 21:45 UTC, ichard26 commented
I didn't break the referenced message fallback out into its own function as I am not convinced it would be a net readability improvement. I don't have a strong opinion on this though.

2023-12-26 19:52 UTC, MrHemlock requested changes
Not sure if I'm being specifically picky or not, but it just seems redundant to check `if message is None:` twice

2023-12-26 19:52 UTC, MrHemlock commented on bot/exts/info/information.py
> +
Is there a particular reason we're doing this in two checks?
```suggestion
        if message is None:
            if (reference := ctx.message.reference) and isinstance(reference.resolved, Message):
                message = reference.resolved

            else:
                await send_denial(ctx, "Missing message argument. Please provide a message ID/link or reply to a message.")
                return

```

2023-12-26 19:52 UTC, MrHemlock commented on bot/exts/info/information.py
> +
Same as above, is there a specific reason for making these separate checks?


```suggestion
        if message is None:
            if (reference := ctx.message.reference) and isinstance(reference.resolved, Message):
                message = reference.resolved

            else:
                await send_denial(ctx, "Missing message argument. Please provide a message ID/link or reply to a message.")
                return

```

2023-12-30 18:42 UTC, wookie184 approved these changes
All looks good to me

2024-03-10 20:21 UTC, ChrisLovering commented
we should really get around to writing this as a d.py convertor in bot-core one of these days. This pattern seems to be used quite often now.

2024-03-10 20:21 UTC, merged