Change color of cancel staff infraction button from green to gray
python-discord/bot pull request #2980
Opened 2024-03-26 18:36 UTC by Robin5605

Closes #2978

2024-03-26 18:42 UTC, vivekashok1221 approved these changes
Thanks :star2:

2024-03-26 19:00 UTC, vivekashok1221 requested changes
Slight nit.

2024-03-26 19:00 UTC, vivekashok1221 commented on bot/exts/moderation/infraction/_views.py
>          """Callback coroutine that is called when the "confirm" button is pressed."""
```suggestion
        """Callback coroutine that is called when the "Ban" button is pressed."""
```
or 
```suggestion
        """Callback coroutine that is called when the button labelled "Ban" is pressed."""
```

2024-03-27 00:14 UTC, ichard26 reviewed
The view class was intentionally designed to be generic, able to be used to request confirmation for any infraction. Consequently, it was named `InfractionConfirmationView`. This change, while a change for the better IMO, restricts the class to ban infractions.

Can we please rename the class to `BanConfirmationView` at least?

2024-05-14 17:11 UTC, Robin5605 commented
@wookie184 I've addressed @ichard26's comment and @vivekashok1221's review. Should be good to go now, let me know if I've missed anything.

2024-05-14 17:56 UTC, vivekashok1221 approved these changes
LGTM :star2:

2024-05-14 17:59 UTC, merged