Fix showing `!source` on tags when tags cog is reloaded
python-discord/bot pull request #3005
Opened 2024-04-06 07:24 UTC by hedyhli

Closes #2022

<img width="800" alt="image" src="https://github.com/python-discord/bot/assets/50042066/783ec7d8-4fc6-41d4-80e9-d43425a35925">

---

<img width="800" alt="image" src="https://github.com/python-discord/bot/assets/50042066/e933bde0-0fab-4565-86d9-ed80ed9e182c">

---

### TLDR

Invoking `!source <tag>` should now work even after the tags cog is reloaded.

### Long description

Previously the source command checks for the source object's class after getting it from the SourceType converter. When the tags cog is reloaded, TagIdentifier is redefined. We were checking whether the old TagIdentifier class (the `type()` of an instance of the old TagIdentifier) equals the newly defined TagIdentifier class. This returns false because the TagIdentifier class is redefined when the tags cog is reloaded, which caused tags, correctly identified by Source converter, to be unable to be identified in the source cog.

The fix takes advantage of the fact that the source converter could correctly identify tags objects even after the tags cog reloads, and use enum comparisons rather than `isinstance`/`type()` to obtain the source type of whatever the source converter returns.

Since we're no longer using the source converter as an actual converter, the function is moved to the source cog instead, and it still works fine.

2024-04-07 22:27 UTC, wookie184 requested changes

2024-04-07 22:27 UTC, wookie184 commented on bot/exts/info/source.py
> +    async def get_source_object(ctx: commands.Context, argument: str) -> (SourceObject, SourceType):
```suggestion
    async def get_source_object(ctx: commands.Context, argument: str) -> tuple[SourceObject, SourceType]:
```

2024-04-14 12:28 UTC, wookie184 approved these changes
Looks great, thanks!

2024-05-21 06:47 UTC, vivekashok1221 approved these changes
LGTM :star2:

2024-05-21 06:50 UTC, merged