Post nomination entries into the voting thread instead of the root
python-discord/bot pull request #3063
Opened 2024-05-21 18:00 UTC by jb3

This change moves us from posting multiple messages in the
nomination-voting channel to instead posting all entries into the voting
thread.

This makes the nomination process guaranteed to be contained within one
root message and one channel, instead of splitting into multiple
messages in the root if we went over the character limit.

It greatly simplifies both the creation and the archival of nomination
votes as we only need to handle one message.

It also means that all nominations are guaranteed to be visible in the
voting thread.

2024-05-21 23:07 UTC, wookie184 requested changes
The `get_review` command will need updating now that `make_review` returns another value:
https://github.com/python-discord/bot/blob/7437d98bfa8287a91857f860567efd748e38e438/bot/exts/recruitment/talentpool/_cog.py#L766
(I don't mind what you make the command do, or even if you want to remove it instead, I don't think it's that useful).

Not tested yet but looking pretty solid, thanks 💪

2024-05-21 23:07 UTC, wookie184 commented on bot/exts/recruitment/talentpool/_review.py
> +# Regex for finding the a nomination, and extracting the nominee.
```suggestion
# Regex for finding a nomination, and extracting the nominee.
```

2024-05-22 01:00 UTC, wookie184 approved these changes
Works like a charm

2024-05-22 02:37 UTC, Xithrius commented on bot/exts/recruitment/talentpool/_review.py
> +        return f"They have **{len(nomination.entries)}** nomination{'s' if plural else ''} this round."
Perhaps?
```suggestion
        entry_count = len(nomination.entries)

        return f"They have **{entry_count}** nomination{'s' if entry_count > 1 else ''} this round."
```

2024-05-22 02:46 UTC, Xithrius approved these changes
Yes.

2024-05-22 02:55 UTC, merged